### ISSUE TITLE
Update license to use the complete BSD-3-clause license text?

### ISSUE THREAD

**Issue by mbrukman** [jthlim/impulse-tracker#1]
Hi Jeff, thanks so much for sharing the source code for Impulse Tracker! I remember using it a lot back in the day. This is a great piece of history for those of us who loved trackers and tracker music.

---

I saw you're using something that looks like the BSD-3-clause license, but it's not *exactly* BSD-3-clause license. Any particular reason for the deviation? The specific change in this project's license only protects the author, but not any contributors. Specifically here's the diff between the [BSD-3-clause license](https://choosealicense.com/licenses/bsd-3-clause/) and this project's license[^1]:

```diff
--- bsd-3.txt	2024-06-15 18:54:07
+++ it.txt	2024-06-15 18:53:20
@@ -8,17 +8,16 @@
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.
 
-3. Neither the name of the copyright holder nor the names of its
-   contributors may be used to endorse or promote products derived from
-   this software without specific prior written permission.
+3. The name of the author may not be used to endorse or promote products
+   derived from this software without specific prior written permission.
 
-THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
-AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
-IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
-DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
-FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
-DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
-SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
-CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
-OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
-OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, 
+INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND 
+FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR 
+BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
+CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
+SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
+INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
+CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
+ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
+POSSIBILITY OF SUCH DAMAGE.
```

Would you mind using the full BSD-3-clause license for your project? This will also have the side benefit of GitHub showing a [license badge on your project](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) which will clearly state it's the BSD-3-clause license; right now, it just says "View license" and links to `LICENSE.TXT`.

If you want the full copy of the BSD-3-clause license, please see: https://choosealicense.com/licenses/bsd-3-clause/

Thanks again!

[^1]: I moved the word "this" to the next line in clause 1 to make the text line up; otherwise, I just ignored the first copyright line, so these are the only meaningful diffs.

**Comment by jthlim** [comment]
Thanks for pointing out the discrepancy - I took a copy of what I thought was a BSD license 10 years ago.

I've updated it now using the GitHub license template, so it shows up as BSD 3 clause in the UI.

**Comment by mbrukman** [comment]
Great, thank you very much!
