### ISSUE TITLE
Time Imformation not showing logs

### ISSUE THREAD

**Issue by BKVad1m** [jthlim/impulse-tracker#11]
In Time information [pressed LShift+Alt+AltGr+RCtrl+Pause] logs not showing before saving. After saving same thing but module time works. I tested with FreeDOS portable following:
```
Motherboard: ASRock 970 Extreme 4
CPU: AMD FX-8320 supported MMX
32GB of RAM
GPU: geForce GTX 1080 [works perfectly with Impulse Tracker]
IT EMS: 32MB
IT Driver: Sound Blaster 16 MMX [SBEMU emulation into Intel HDA]
```

**Comment by jthlim** [comment]
That is by design -- timestamps are only saved when a file is written.
