### ISSUE TITLE
[XM] overflow B-0 and C00 command broken

### ISSUE THREAD

**Issue by BKVad1m** [jthlim/impulse-tracker#12]
I can't upload files on my mobile

**Comment by BKVad1m** [comment]
https://github.com/user-attachments/assets/d246d133-6430-4973-bbfe-5fe034012aa1

B-0 ► ••• (no note)

**Comment by BKVad1m** [comment]
also update the copyright years as 1995-2024

**Comment by BKVad1m** [comment]
[forste_hand_1.zip](https://github.com/user-attachments/files/17457725/forste_hand_1.zip)
This module is occurred

**Comment by cs127** [comment]
[As Jeffrey said in my PR](https://github.com/jthlim/impulse-tracker/pull/10#issuecomment-2424527775), this repository is only meant for preserving the source code, there is no active development going on.

**Comment by jthlim** [comment]
Note: From the README:

Note that this repository is purely sharing what used to be -- there is no active development, and changes/fixes will not be merged other than issues preventing build.
