### ISSUE TITLE
Readme.MD could reference the original blog posts?

### ISSUE THREAD

**Issue by esaruoho** [jthlim/impulse-tracker#2]
https://roartindon.blogspot.com/2014/02/20-years-of-impulse-tracker.html
https://roartindon.blogspot.com/2014/03/20-years-of-impulse-tracker-part-2.html
https://roartindon.blogspot.com/2014/10/20-years-of-impulse-tracker-part-3.html
https://roartindon.blogspot.com/2014/12/20-years-of-impulse-tracker-part-4.html

**Comment by jthlim** [comment]
Done, thanks  for the suggestion.
