### ISSUE TITLE
itwav.drv outputs .000 extension instead of .wav? and only .000, never .001 etc?

### ISSUE THREAD

**Issue by esaruoho** [jthlim/impulse-tracker#7]
what's the reason `/s20` outputs a filename.000 instead of filen000.wav? and is there ever a case where .001 or .002 is rendered?

i finally (finally!) have my network drive running, so can directly output from diskwriter to network drive, where i can get the sample into another legacy music making app (logic audio platinum 5.5.1) but now i have to rename them by hand every time.
it wouldn't be such a big deal, if it was a case of: first render = filename.000 -- second render = filename.001 .. etc

then i could just rename them in a batch. but it will keep overwriting filename.000 on every diskwrite. 

what am i missing here? @jthlim

**Comment by esaruoho** [comment]
ok, a penny dropped and now i understand the ".000"

it is because of the pattern that i'm on is 000.
so if i go to pattern 001, and diskwrite, it'll diskwrite .001".
that helps, thanks!

**Comment by esaruoho** [comment]
but still weirds me out that it doesn't diskwrite to .wav extension, instead .patternnumber

**Comment by jthlim** [comment]
If you play mysong.it, it'll save mysong.wav
If you play pattern 0 from mysong.it, it'll save mysong.000

This was a design choice at the time, with 8.3 filename limitations of DOS.

**Comment by esaruoho** [comment]
> If you play mysong.it, it'll save mysong.wav If you play pattern 0 from mysong.it, it'll save mysong.000
> 
> This was a design choice at the time, with 8.3 filename limitations of DOS.

thanks! that makes sense. :)

took me a while and only came across the "006 = .006" by accident since i happened to have a track with orderlist 006 - otherwise i would've thought it's .000 forvever :)
