### ISSUE TITLE
Version number?

### ISSUE THREAD

**Issue by cs127** [jthlim/impulse-tracker#8]
This might be a bit of a weird question, but what exactly is the version number?

I tried out different versions available on modland, and these were the results for the `Cwt/v` / `TRACKERVERSION` values:
* 2.14: $0214
* 2.14p3: $0216
* 2.14p4: $0217
* 2.14p5: $0217
* "2.15" (leaked?): $0216
* this repo: $0217

How do the version numbers work exactly? Should the version in this repo be referred to as 2.17?

(For context, I'm going to submit a patch to OpenMPT's version detection, and I need to specify a version number for files that are made with this version. Is 2.17 correct?)

**Comment by jthlim** [comment]
With apologies, it's been almost 30 years and really don't remember anymore.

I guess I incremented it at various times in the past -- this was all written before I had source control, so I don't have any history or changesets I can inspect
