### ISSUE TITLE
Unable to compile GUS and WSS drivers due to missing symbol

### ISSUE THREAD

**Issue by cs127** [jthlim/impulse-tracker#9]
The assembler complains about `UPDATESAMPLELOCATION` being undefined when it is called in `gus.inc` and `wssdrv.asm`, preventing the following drivers from being compiled:
* `gushiqdr`
* `gushiq2`
* `gusdrv2`
* `wssdrv`
* `wssdrv2`

**Comment by jthlim** [comment]
Seems like sometime, somewhere in the last 20 years, a name got deleted, and I didn't notice.

https://github.com/jthlim/impulse-tracker/commit/b09e0ef66e9207c2ceeca14a78fd077143d1f934 hopefully fixes it.
